"""The Territory bench's engine is the approved prototype, byte for byte."""
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PROTO = ROOT / "tools" / "territory-prototype"
ENGINE = ROOT / "axibridge" / "static" / "js" / "territory" / "engine.js"
PARTS = ["t_head.js", "t_flood.js", "t_body.js", "t_hand.js", "t_forms.js",
         "t_graph.js", "t_v5.js", "t_meander.js", "t_density.js"]


def test_generated_engine_is_current():
    """engine.js must be regenerated by build.sh whenever a t_*.js part changes."""
    body = "".join((PROTO / p).read_text() for p in PARTS)
    assert body in ENGINE.read_text(), "run tools/territory-prototype/build.sh"


@pytest.mark.skipif(not shutil.which("node"), reason="Node unavailable")
def test_engine_matches_the_approved_recipes():
    # Pinned from the prototype (CJS) on 2026-09-29: seeds 1-4 at density 0 and at the Version 10 max recipe.
    script = """
    import assert from 'node:assert/strict'; import crypto from 'node:crypto';
    import {runTerritory, randomSheet, MEANDER_MACROS} from './axibridge/static/js/territory/engine.js';
    const B = {loose:.5,yieldP:.5,wander:1,reach:15,spread:.7,eps:.03,borders:true,outer:true,voids:true,interior:false,disregard:.15,hyst:25,render:'meander'};
    const V10 = {...MEANDER_MACROS,density:1,continue:1,cover:0.45,planes:0.15,mutate:1,slash:1,surprise:1,ink:60};
    const hash = d => { const h = crypto.createHash('sha1'); for (let s = 1; s <= 4; s++) { const sh = randomSheet(s);
      h.update(JSON.stringify(runTerritory(sh.cores, {...B, ...d, camps: Math.max(2, sh.camps)}, s, 'reversed').lines)); } return h.digest('hex').slice(0, 12); };
    assert.equal(hash({...MEANDER_MACROS}), 'b45260fbdda1');
    assert.equal(hash(V10), '69348711b6f5');
    // Version 8 planes: the same engine with no planes/mutate keys (the bench's 'Version 8 planes' fill)
    assert.equal(hash({...MEANDER_MACROS,density:1,continue:1,cover:0.5,slash:1,surprise:1,ink:60}), '5eb5c5e66e06');
    """
    subprocess.run(["node", "--input-type=module", "-e", script], cwd=ROOT, check=True, timeout=120)
