#!/bin/sh
# Rebuild the engine and the single-file page (see README), and the ES-module copy the axibridge bench imports.
cd "$(dirname "$0")"
cat t_head.js t_flood.js t_body.js t_hand.js t_forms.js t_graph.js t_v5.js t_meander.js t_density.js > territory-engine.js
python3 -c "p=open('territory-page.html').read(); e=open('territory-engine.js').read(); open('territory.html','w').write(p.replace('/*ENGINE*/',e))"
mkdir -p ../../axibridge/static/js/territory
{ echo '// GENERATED by tools/territory-prototype/build.sh from t_*.js — edit those, not this file.'
  echo '/* eslint-disable */'
  cat territory-engine.js
  echo 'export { runTerritory, randomSheet, MEANDER_MACROS, polyLen };'; } > ../../axibridge/static/js/territory/engine.js
